<?php

session_start();

if(!isset($_SESSION['username']))
{
    header("Location:../login.php");
    exit();
}

require_once("../db_connect.php");

$patients =
mysqli_num_rows(
mysqli_query($conn,
"SELECT * FROM patients")
);

$records =
mysqli_num_rows(
mysqli_query($conn,
"SELECT * FROM medical_records")
);

$appointments =
mysqli_num_rows(
mysqli_query($conn,
"SELECT * FROM appointments")
);

$referrals =
mysqli_num_rows(
mysqli_query($conn,
"SELECT * FROM referrals")
);

$users =
mysqli_num_rows(
mysqli_query($conn,
"SELECT * FROM users")
);

?>

<!DOCTYPE html>

<html>

<head>

<title>System Reports</title>

<link href=
"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
rel="stylesheet">

<style>

@media print
{
button,
.btn
{
display:none;
}
}

</style>

</head>

<body>

<div class="container mt-5">

<h2>Medical Collaborative System Report</h2>

<p>

Date Generated:

<?php echo date("d-m-Y h:i A"); ?>

</p>

<p>

Generated By:

<?php echo $_SESSION['username']; ?>

</p>

<hr>

<table class="table table-striped table-hover table-bordered">

<tr>
<th>Item</th>
<th>Total</th>
</tr>

<tr>
<td>Total Patients</td>
<td><?php echo $patients; ?></td>
</tr>

<tr>
<td>Total Medical Records</td>
<td><?php echo $records; ?></td>
</tr>

<tr>
<td>Total Appointments</td>
<td><?php echo $appointments; ?></td>
</tr>

<tr>
<td>Total Referrals</td>
<td><?php echo $referrals; ?></td>
</tr>

<tr>
<td>Total Users</td>
<td><?php echo $users; ?></td>
</tr>

</table>

<button
onclick="window.print()"
class="btn btn-success">

Print Report

</button>

<a
href="../dashboard.php"
class="btn btn-primary">

Back Dashboard

</a>

</div>

</body>

</html>